In [1]:
!pip install tensorflow


   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/390.3 MB 9.5 MB/s eta 0:00:41
   ---------------------------------------- 3.4/390.3 MB 9.6 MB/s eta 0:00:41
   ---------------------------------------- 4.7/390.3 MB 8.6 MB/s eta 0:00:45
    --------------------------------------- 6.6/390.3 MB 8.9 MB/s eta 0:00:43
    --------------------------------------- 8.7/390.3 MB 8.8 MB/s eta 0:00:44
   - -------------------------------------- 10.7/390.3 MB 9.1 MB/s eta 0:00:42
   - -------------------------------------- 12.3/390.3 MB 8.9 MB/s eta 0:00:43
   - -------------------------------------- 13.6/390.3 MB 8.6 MB/s eta 0:00:45
   - -------------------------------------- 13.9/390.3 MB 8.3 MB/s eta 0:00:46
   - -------------------------------------- 16.0/390.3 MB 7.8 MB/s eta 0:00:48
   - -------------------------------------- 18.6/390.3 MB 8.2 MB/s eta 0:00:46
   -- ------------------------------------- 20.4/390.3 MB 8.2 MB/

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain 0.2.16 requires numpy<2.0.0,>=1.26.0; python_version >= "3.12", but you have numpy 2.0.2 which is incompatible.
langchain-community 0.2.16 requires numpy<2.0.0,>=1.26.0; python_version >= "3.12", but you have numpy 2.0.2 which is incompatible.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
import tensorflow as tf


ModuleNotFoundError: No module named 'tensorflow'

In [5]:
pip install --upgrade notebook


  Obtaining dependency information for notebook from https://files.pythonhosted.org/packages/46/77/53732fbf48196af9e51c2a61833471021c1d77d335d57b96ee3588c0c53d/notebook-7.2.2-py3-none-any.whl.metadata
  Obtaining dependency information for jupyter-server<3,>=2.4.0 from https://files.pythonhosted.org/packages/57/e1/085edea6187a127ca8ea053eb01f4e1792d778b4d192c74d32eb6730fed6/jupyter_server-2.14.2-py3-none-any.whl.metadata
  Obtaining dependency information for jupyterlab-server<3,>=2.27.1 from https://files.pythonhosted.org/packages/54/09/2032e7d15c544a0e3cd831c51d77a8ca57f7555b2e1b2922142eddb02a84/jupyterlab_server-2.27.3-py3-none-any.whl.metadata
  Obtaining dependency information for jupyterlab<4.3,>=4.2.0 from https://files.pythonhosted.org/packages/f0/04/853abc46fef36afd4e5f9a4fd1fbc1b477f910a29bb71711b6653098b703/jupyterlab-4.2.6-py3-none-any.whl.metadata
  Obtaining dependency information for jupyter-events>=0.9.0 from https://files.pythonhosted.org/packages/a5/94/059180ea70a9a32

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\SAJID\\.jupyter\\anaconda.installed\\Lib\\site-packages\\~mq\\backend\\cython\\context.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [ ]:
Data Load

**Loading Data**

In [7]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

ModuleNotFoundError: No module named 'tensorflow'

**Network Architecture Design**

In [17]:
from tensorflow.keras import models
from tensorflow.keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(784,)))
network.add(layers.Dense(10, activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**Network Compilation**

In [18]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

**Data Transformed as per required by the nueral network**

In [19]:
train_images = train_images.reshape((60000, 784))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 784))
test_images = test_images.astype('float32') / 255

In [20]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [21]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [22]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [23]:
network.fit(train_images, train_labels, epochs=10, batch_size=128)

Epoch 1/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.8734 - loss: 0.4410
Epoch 2/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9654 - loss: 0.1158
Epoch 3/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9771 - loss: 0.0752
Epoch 4/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9853 - loss: 0.0508
Epoch 5/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9902 - loss: 0.0357
Epoch 6/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9918 - loss: 0.0287
Epoch 7/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9939 - loss: 0.0208
Epoch 8/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9958 - loss: 0.0150
Epoch 9/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9970 - loss: 0.0114
Epoch 10/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9980 - loss: 0.0083


In [24]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9775 - loss: 0.0861


In [25]:
test_images[0].shape

(784,)

In [28]:


image = test_images[0].reshape(1,784)
probabilities = network.predict(image)
probabilities.argmax()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


7

In [27]:
probabilities

array([[1.8722306e-10, 1.0561093e-11, 1.1904306e-07, 5.3034398e-07,
        1.4434866e-14, 5.6757371e-10, 2.3786878e-13, 9.9999940e-01,
        1.5189233e-09, 5.2126250e-09]], dtype=float32)

In [ ]:
test_images[0].shape

(784,)

In [29]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [37]:
import keras
import numpy as np
image = keras.utils.load_img('six.png')
from PIL import Image
import numpy as np

# Load the image using PIL
image = Image.open('six.png')

# Convert the image to grayscale
grayscale_image = image.convert('L')  # 'L' mode is for grayscale

input_arr = keras.utils.img_to_array(grayscale_image)
print(input_arr.shape)
input_arr = input_arr.reshape(1,784)
predictions = network.predict(input_arr)

(28, 28, 1)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [38]:
predictions

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

In [40]:
predictions.argmax()

6

In [ ]:
test_images[8].reshape(1,784).shape


(1, 784)

In [42]:
import keras
import numpy as np
def classify_image(img):

  image = keras.utils.load_img(img ,grayscale=True)

  input_arr = keras.utils.img_to_array(image)

  input_arr = input_arr.reshape(1,784)
  predictions = network.predict(input_arr)

  return predictions.argmax(), predictions

In [43]:
classify_image('six.png')

TypeError: load_img() got an unexpected keyword argument 'grayscale'

In [44]:
network.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 512)                 │         401,920 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           5,130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 814,102 (3.11 MB)

 Trainable params: 407,050 (1.55 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 407,052 (1.55 MB)